### ISSUE TITLE
没效果啊，还是翻不了墙

### ISSUE THREAD

**Issue by luckypoem** [shadowsocks/shadowsocks-iOS#118]
hi,
我看了https://github.com/shadowsocks/shadowsocks-iOS/wiki/Help 的As a global proxy部分，按其内容在我的IPHONE(系统为IOS8.0)设置了，但是没效果啊，还是翻不了墙。如何解决？
谢谢。
我直接在shadowsocks-iOS里翻墙是无问题的。

**Comment by loadmemo** [comment]
Same issue with #111 , you should waiting the new version.

**Comment by oscarqht** [comment]
According to the document, the global proxy mode "Only works for a few minutes. Due to iOS restrictions, Shadowsocks can't keep running in the background. It's killed after you leave it for a while. To keep it running for an extended period of time, you have to come back to the Shadowsocks app every few minutes."

Even it works, it only works for a while due to iOS background app restriction. Is it possible to utilize iOS's [background execution api](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW5) to keep the proxy running in background?
